apiVersion: v1
kind: Service
metadata:
  name: pod-a-service
spec:
  selector:
    app: pod-a
  ports:
    - protocol: TCP
      port: 80  # Expose Port 80
      targetPort: 80  # Port on the container
  clusterIP: None 