apiVersion: v1
kind: Service
metadata:
  name: pod-b-service
spec:
  selector:
    app: pod-b
  ports:
    - protocol: TCP
      port: 80        # Port for internal communication within the cluster
      targetPort: 80  # Container's port
      nodePort: 30000 # Port exposed on the node (external)
  type: NodePort