apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx111
spec:
  replicas: 3  # Number of pods you want to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.0  # You can specify the image you want to use
        ports:
        - containerPort: 80