apiVersion: v1
kind: Service
metadata:
  name: pod-1-service
spec:
  selector:
    app: pod-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Expose on this NodePort
  type: NodePort