apiVersion: v1
kind: Service
metadata:
  name: pod-2-service
spec:
  selector:
    app: pod-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004  # Expose on this NodePort
  type: NodePort